# Generated by Django 5.1.4 on 2025-01-20 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo_Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cargo_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Container_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_type", models.CharField(max_length=100)),
                ("container_no", models.CharField(max_length=100)),
                ("truck_planned", models.CharField(max_length=100)),
                ("mtn", models.IntegerField()),
                ("commodity", models.CharField(max_length=100)),
                ("no_of_packages", models.IntegerField()),
                ("seal_no", models.CharField(max_length=100)),
                ("invoice_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="File_Ref_No",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="From_Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="To_Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Job_Information",
            fields=[
                ("payment_after", models.IntegerField()),
                ("bill_on", models.DateField()),
                ("contract_type", models.CharField(max_length=100)),
                ("contract_date", models.DateField()),
                ("job_no", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.IntegerField()),
                ("cargo_job_description", models.CharField(max_length=100)),
                ("head_of_contract", models.CharField(max_length=100)),
                ("loading_point", models.CharField(max_length=100)),
                ("offloading_point", models.CharField(max_length=100)),
                (
                    "cargo_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.cargo_classification",
                    ),
                ),
                (
                    "cargo_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.cargo_type"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="erp.client"
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.from_location",
                    ),
                ),
                (
                    "lot_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.file_ref_no",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobFile",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "container_details",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.container_details",
                    ),
                ),
                (
                    "job_information",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.job_information",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job_information",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_info",
                to="erp.jobfile",
            ),
        ),
        migrations.AddField(
            model_name="container_details",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="container_info",
                to="erp.jobfile",
            ),
        ),
        migrations.CreateModel(
            name="Loose_Cargo_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_classification", models.CharField(max_length=100)),
                ("make", models.CharField(max_length=100)),
                ("chasis_no", models.CharField(max_length=100)),
                ("truck_planned", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("mtn", models.IntegerField()),
                ("engine_no", models.CharField(max_length=100)),
                ("commodity", models.CharField(max_length=100)),
                ("no_of_packages", models.IntegerField()),
                ("invoice_no", models.CharField(max_length=100)),
                (
                    "job_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loose_cargo_info",
                        to="erp.jobfile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobfile",
            name="loose_cargo_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.loose_cargo_information",
            ),
        ),
        migrations.AddField(
            model_name="job_information",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.route"
            ),
        ),
        migrations.CreateModel(
            name="Supplier_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_ref_no", models.CharField(max_length=100)),
                ("consignor", models.CharField(max_length=100)),
                ("consignee", models.CharField(max_length=100)),
                (
                    "job_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_info",
                        to="erp.jobfile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobfile",
            name="supplier_information",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.supplier_information",
            ),
        ),
        migrations.AddField(
            model_name="job_information",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.to_location"
            ),
        ),
    ]
