# Generated by Django 5.1.4 on 2024-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_type", models.CharField(max_length=100)),
                ("container_no", models.CharField(max_length=100)),
                ("truck_planned", models.CharField(max_length=100)),
                ("mtn", models.IntegerField()),
                ("commodity", models.CharField(max_length=100)),
                ("no_of_packages", models.IntegerField()),
                ("seal_no", models.CharField(max_length=100)),
                ("invoice_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Job_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_after", models.IntegerField()),
                ("bill_on", models.DateField()),
                ("contract_type", models.CharField(max_length=100)),
                ("contract_date", models.DateField()),
                ("job_no", models.CharField(max_length=100)),
                ("route", models.CharField(max_length=100)),
                ("from_location", models.CharField(max_length=100)),
                ("to_location", models.CharField(max_length=100)),
                ("weight", models.IntegerField()),
                ("cargo_classification", models.CharField(max_length=100)),
                ("cargo_type", models.CharField(max_length=100)),
                ("cargo_job_description", models.CharField(max_length=100)),
                ("client", models.CharField(max_length=100)),
                ("head_of_contract", models.CharField(max_length=100)),
                ("loading_point", models.CharField(max_length=100)),
                ("lot_no", models.CharField(max_length=100)),
                ("offloading_point", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Loose_Cargo_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_classification", models.CharField(max_length=100)),
                ("make", models.CharField(max_length=100)),
                ("chasis_no", models.CharField(max_length=100)),
                ("truck_planned", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("mtn", models.IntegerField()),
                ("engine_no", models.CharField(max_length=100)),
                ("commodity", models.CharField(max_length=100)),
                ("no_of_packages", models.IntegerField()),
                ("invoice_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_ref_no", models.CharField(max_length=100)),
                ("consignor", models.CharField(max_length=100)),
                ("consignee", models.CharField(max_length=100)),
            ],
        ),
    ]
