# Generated by Django 5.1.4 on 2024-12-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo_Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cargo_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="File_Ref_No",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="From_Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="To_Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="job_information",
            name="id",
        ),
        migrations.AlterField(
            model_name="job_information",
            name="job_no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="cargo_classification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="erp.cargo_classification",
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="cargo_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.cargo_type"
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.client"
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="lot_no",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.file_ref_no"
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="from_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.from_location"
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.route"
            ),
        ),
        migrations.AlterField(
            model_name="job_information",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.to_location"
            ),
        ),
    ]
