# Generated by Django 5.1.4 on 2024-12-25 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_cargo_classification_cargo_type_client_file_ref_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFile",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "container_details",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.container_details",
                    ),
                ),
                (
                    "job_information",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.job_information",
                    ),
                ),
                (
                    "loose_cargo_information",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.loose_cargo_information",
                    ),
                ),
                (
                    "supplier_information",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.supplier_information",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="container_details",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="container_info",
                to="erp.jobfile",
            ),
        ),
        migrations.AddField(
            model_name="job_information",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_info",
                to="erp.jobfile",
            ),
        ),
        migrations.AddField(
            model_name="loose_cargo_information",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loose_cargo_info",
                to="erp.jobfile",
            ),
        ),
        migrations.AddField(
            model_name="supplier_information",
            name="job_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_info",
                to="erp.jobfile",
            ),
        ),
    ]
