# Generated by Django 5.1.4 on 2025-01-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0003_jobfile_container_details_job_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job_information",
            name="lot_no",
        ),
        migrations.RemoveField(
            model_name="supplier_information",
            name="file_ref_no",
        ),
        migrations.DeleteModel(
            name="File_Ref_No",
        ),
    ]
