# Generated by Django 5.1.4 on 2025-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_remove_job_information_lot_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfile",
            name="job_file_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
