# Generated by Django 5.1.4 on 2025-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_jobfile_job_file_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobfile",
            name="job_file_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
